apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-votting-app-wk
  labels:
    app: ex-votting-app-wk
  namespace: ex-votting-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex-votting-app-wk
  template:
    metadata:
      labels:
        app: ex-votting-app-wk
    spec:
      containers:
        - name: ex-votting-app-wk
          image: acraksdem.azurecr.io/ex-votting-app-img:latest
          ports:
            - containerPort: 8080