apiVersion: v1
kind: Service
metadata:
  name: ex-votting-app-wk
  namespace: ex-votting-app-ns
spec:
  type: LoadBalancer
  selector:
    app: ex-votting-app-wk
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080